# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fasttransport',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/fasttransport',
                'lib_path': 'fasttransport'},
  'syms': {'fasttransport.core': {'fasttransport.core.foo': ('core.html#foo', 'fasttransport/core.py')}}}
