"""Sync and async HTTP transports over httpx2, and base classes for small REST clients

Docs: https://AnswerDotAI.github.io/fasttransport/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['ProtocolError', 'AsyncTransport', 'SyncTransport', 'HttpCli', 'AsyncHttpCli']

# %% ../nbs/00_core.ipynb #ca352892
from fastcore.meta import delegates
import httpx2, json as jsonlib
from functools import partial
from contextlib import nullcontext
from httpx2 import EventSource

# %% ../nbs/00_core.ipynb #09ff28d5
class ProtocolError(Exception):
    "Raised when a stream payload does not match the expected protocol shape."

# %% ../nbs/00_core.ipynb #a3a6efd9
class AsyncTransport:
    "Thin async transport over httpx2. By default each request gets a fresh client, so nothing is tied to an event loop; pass `client=` to use a persistent client that you manage (and close via `aclose`)."
    def __init__(self, *, timeout=60.0, client=None, base_headers=None, follow_redirects=True, verify=True):
        self.timeout,self.client,self.base_headers,self.follow_redirects,self.verify = timeout,client,base_headers or {},follow_redirects,verify

    def _client(self):
        if self.client: return nullcontext(self.client)
        return httpx2.AsyncClient(timeout=self.timeout, follow_redirects=self.follow_redirects, verify=self.verify)

    async def aclose(self):
        if self.client: await self.client.aclose()

    def _headers(self, headers=None): return {**self.base_headers, **(headers or {})}

    def _request_headers(self, headers=None, *, files=None):
        "Merge headers and drop explicit content-type for multipart uploads."
        h = self._headers(headers)
        if files is not None:
            # Let httpx compute multipart/form-data with boundary.
            for k in list(h):
                if k.lower() == "content-type": h.pop(k, None)
        return h

    @staticmethod
    def _decode(resp):
        "Decode response body using content type."
        if not resp.content: return None
        ctype = (resp.headers.get("content-type") or "").lower()
        if "application/json" in ctype or ctype.endswith("+json"): return resp.json()
        if ctype.startswith("text/") or "application/x-ndjson" in ctype: return resp.text
        return resp.content

    async def request(self, method, url, *, headers=None, params=None, json=None, data=None,
        files=None, content=None, raw=False):
        "Execute a request and decode JSON/text/binary response."
        async with self._client() as client:
            resp = await client.request(method, url, headers=self._request_headers(headers, files=files),
                params=params, json=json, data=data, files=files, content=content)
            try: resp.raise_for_status()
            except httpx2.HTTPStatusError as e:
                e.args = (f"{e}\n{resp.text}",)
                raise
            return resp if raw else self._decode(resp)

    async def stream(self, method, url, *, headers=None, params=None, json=None, data=None, files=None):
        async with self._client() as client:
            async with client.stream(method, url, headers=self._request_headers(headers, files=files),
                params=params, json=json, data=data, files=files) as resp:
                try: resp.raise_for_status()
                except httpx2.HTTPStatusError as e:
                    try: await resp.aread()
                    except Exception: pass
                    e.args = (f"{e}\n{resp.text}",)
                    raise
                if 'content-type' not in resp.headers: resp.headers['content-type'] = 'text/event-stream'  # some backends (codex) omit it; the old parser never checked
                events = aiter(EventSource(resp, max_event_size=None))
                try:
                    async for event in events:
                        if not event.data: continue
                        if event.data == "[DONE]": return
                        try: raw = jsonlib.loads(event.data)
                        except jsonlib.JSONDecodeError as e: raise ProtocolError(f"Invalid SSE JSON: {e}") from e
                        if isinstance(raw, dict): yield raw
                        else: raise ProtocolError(f"Expected SSE JSON object, got {type(raw).__name__}")
                finally: await events.aclose()

# %% ../nbs/00_core.ipynb #4df92440
class SyncTransport(AsyncTransport):
    "Sync twin of `AsyncTransport`, over `httpx2.Client`. SSE needs the async transport, so `stream` raises."
    def stream(self, *args, **kwargs):
        raise TypeError("SSE streaming needs `AsyncTransport`; drive it from sync code with `fastcore.aio.iter_sync`")

    def _client(self):
        if self.client: return nullcontext(self.client)
        return httpx2.Client(timeout=self.timeout, follow_redirects=self.follow_redirects, verify=self.verify)

    def close(self):
        if self.client: self.client.close()

    def request(self, method, url, *, headers=None, params=None, json=None, data=None,
        files=None, content=None, raw=False):
        "Sync version of `AsyncTransport.request`."
        with self._client() as client:
            resp = client.request(method, url, headers=self._request_headers(headers, files=files),
                params=params, json=json, data=data, files=files, content=content)
            try: resp.raise_for_status()
            except httpx2.HTTPStatusError as e:
                e.args = (f"{e}\n{resp.text}",)
                raise
            return resp if raw else self._decode(resp)

# %% ../nbs/00_core.ipynb #4e549f4c
class HttpCli:
    "Small REST client over `SyncTransport`: verb attributes (`get`, `post`, `put`, `patch`, `delete`) call `body`, with kwargs as the payload"
    tcls = SyncTransport
    _verbs = ('get','post','put','patch','delete')
    @delegates(SyncTransport)
    def __init__(self, base_url, transport=None, **kwargs):
        self.base_url = base_url.rstrip('/')
        self.transport = transport or self.tcls(**kwargs)

    def _url(self, path): return f"{self.base_url}/{str(path).lstrip('/')}" if path else self.base_url
    def _req(self, method, path='', **kw): return self.transport.request(method, self._url(path), **kw)
    def body(self, method, path='', /, params=None, json=None, useparams_=False, **kw):
        "Send a request with `kw` merged into `params` if `useparams_`, else into `json`"
        if useparams_: params = {**(params or {}), **kw}
        else: json = {**(json or {}), **kw}
        return self._req(method, path, params=params, json=json or None)
    def __getattr__(self, name):
        if name not in self._verbs: raise AttributeError(name)
        return partial(self.body, name.upper(), useparams_=name in ('get','delete'))
    def __dir__(self): return [*super().__dir__(), *self._verbs]

class AsyncHttpCli(HttpCli):
    "Async twin of `HttpCli`, over `AsyncTransport`: the verbs return awaitables"
    tcls = AsyncTransport
    async def _req(self, method, path='', **kw): return await self.transport.request(method, self._url(path), **kw)
